// Code generated by "stringer -type=EventType"; DO NOT EDIT

package midi

import "fmt"

const _EventType_name = "SysexMetaMidi"

var _EventType_index = [...]uint8{0, 5, 9, 13}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return fmt.Sprintf("EventType(%d)", i)
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
